# Generated by Django 5.2.7 on 2026-02-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linbook', '0002_friend_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='avatar',
            field=models.ImageField(default='default_avatar.png', upload_to='friends/'),
        ),
    ]
