# Generated by Django 5.2.7 on 2026-02-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linbook', '0003_alter_friend_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='avatar',
            field=models.ImageField(blank=True, default='friends/default_avatar.png', null=True, upload_to='friends/'),
        ),
    ]
