# Generated by Django 5.2.7 on 2026-02-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linbook', '0004_alter_friend_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='shares_count',
            field=models.IntegerField(default=0),
        ),
    ]
