# Generated by Django 5.2.7 on 2026-02-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linbook', '0005_post_comments_count_post_shares_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='影片標題')),
                ('file', models.FileField(upload_to='videos/', verbose_name='影片檔案')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/', verbose_name='影片封面')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
            ],
            options={
                'verbose_name': '影片',
                'verbose_name_plural': '影片',
            },
        ),
    ]
