# Generated by Django 5.2.7 on 2026-02-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linbook', '0008_alter_post_created_at_alter_profile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.CharField(default='1785年8月30日', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(default='大清朝廷', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_city',
            field=models.CharField(default='福建省侯官縣', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='男', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='hometown',
            field=models.CharField(default='福建福州', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_status',
            field=models.CharField(default='已婚', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(default='嘉慶進士', max_length=100),
        ),
    ]
