# Generated by Django 5.2.7 on 2026-02-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linbook', '0010_lifeevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='linbook.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.CharField(default='1785年8月30日', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(default='大清朝廷', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_city',
            field=models.CharField(default='福建省侯官縣', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='男', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hometown',
            field=models.CharField(default='福建福州', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_status',
            field=models.CharField(default='已婚', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(default='嘉慶進士', max_length=100, null=True),
        ),
    ]
