# Generated by Django 5.2.7 on 2026-02-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linbook', '0012_alter_profile_birthday_alter_profile_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(verbose_name='留言時間'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.TextField(verbose_name='發帖時間'),
        ),
    ]
